const list = [
    "Oui.",
    "Non.",
    "Peut-être.",
    "Redemande plus tard.",
    "Certainement.",
    "Absolument pas.",
    "Je ne pense pas.",
    "Oui, mais peu probable.",
    "Non, sans aucun doute.",
    "C’est certain.",
    "Ne compte pas dessus.",
    "Sans aucun doute.",
    "Oui, assurément.",
    "Très douteux.",
    "Oui, en temps voulu.",
    "Impossible.",
    "Les perspectives sont bonnes.",
    "Les perspectives ne sont pas bonnes.",
    "Très probable.",
    "Pas du tout.",
    "Oui, mais avec prudence.",
    "Je ne suis pas sûr, réessaie.",
    "Oui, définitivement.",
    "Non, définitivement.",
    "Probablement.",
    "Probablement pas.",
    "La réponse est floue, réessaie.",
    "Mes sources disent non.",
    "Mes sources disent oui.",
    "Ce n’est pas clair, redemande plus tard.",
    "Tu peux compter dessus.",
    "Oui, mais avec des efforts.",
    "Non, mais il reste de l’espoir.",
    "C’est incertain.",
    "Concentre-toi et redemande.",
    "Oui, mais cela prendra du temps.",
    "Non, et il n’y a aucun espoir.",
    "Peut-être.",
    "Oui, si tu le veux vraiment.",
    "Non, et tu devrais reconsidérer.",
    "Tu devrais demander a Speedy.",
    "Tu devrais demander a Zeleph.",
    "Absolument.",
    "Peut-être pas.",
    "Je ne suis pas sûr, mais c’est possible.",
    "Oui, mais seulement si les conditions sont réunies.",
    "Non, mais les choses peuvent changer.",
    "L’avenir est incertain.",
    "Cela semble probable.",
    "Les étoiles sont alignées.",
    "Les étoiles ne sont pas alignées.",
    "Oui, mais cela demandera des efforts.",
    "Non, et tu devrais éviter.",
    "Demande à quelqu’un d’autre.",
    "Les signes indiquent oui.",
    "Les signes indiquent non.",
    "C’est une possibilité.",
    "Très improbable.",
    "Certainement pas.",
    "Oui, mais sois préparé.",
    "Non, et il vaut mieux éviter.",
    "Peut-être, mais c’est incertain.",
    "La réponse est en toi.",
    "Fais confiance à ton intuition.",
    "L’univers dit oui.",
    "L’univers dit non.",
    "Oui, mais avec quelques réserves.",
    "Non, et ça n’en vaut pas la peine.",
    "Tout indique oui.",
    "Tout indique non.",
    "Le résultat est positif.",
    "Le résultat est négatif.",
    "Procède avec prudence.",
    "Vas-y et essaie.",
    "Le moment n’est pas propice.",
    "Le moment est propice.",
    "Oui, mais attends-toi à des obstacles.",
    "Non, et c’est peu probable.",
    "L’avenir est prometteur.",
    "L’avenir est sombre.",
    "C’est une bonne idée.",
    "Ce n’est pas une bonne idée.",
    "La réponse va te surprendre.",
    "Tu es sur la bonne voie.",
    "Tu n’es pas sur la bonne voie.",
    "Oui, mais considère des alternatives.",
    "Non, et c’est une mauvaise idée.",
    "Peut-être, mais avance prudemment.",
    "Oui, si tu prends les bonnes mesures.",
    "Non, et ce n’est pas conseillé.",
    "La décision t’appartient.",
    "Cherche des signes autour de toi.",
    "Oui, si les conditions sont remplies.",
    "Non, mais ça vaut la peine d’essayer.",
    "Tout indique oui.",
    "Tout indique non.",
    "Oui, mais avec quelques difficultés.",
    "Non, et il vaut mieux éviter.",
    "Oui, mais prépare-toi à des changements.",
    "Non, et cela ne changera probablement pas.",
    "Ce n’est pas clair pour l’instant.",
    "La réponse n’est pas claire.",
    "Oui, avec une forte probabilité.",
    "Non, avec une grande certitude.",
    "Oui, mais cela demandera des efforts.",
    "Non, et les chances sont minces.",
    "Oui, mais les choses pourraient changer.",
    "Non, et il vaut mieux attendre.",
    "Les perspectives sont incertaines.",
    "La situation est instable.",
    "Oui, si tu agis bientôt.",
    "Non, et cela ne vaut pas la peine d’être poursuivi.",
    "Oui, mais avec beaucoup d’efforts.",
    "Non, et il est peu probable que cela réussisse.",
    "La situation semble prometteuse.",
    "La situation semble désespérée.",
    "Oui, mais prends en compte tous les facteurs.",
    "Non, et ce n’est pas conseillé.",
    "Oui, si tu avances doucement.",
    "Non, et il vaut mieux éviter.",
    "Oui, mais avec prudence.",
    "Non, et il vaut mieux reconsidérer."
];


module.exports.run = async(client, message) => {
    message.reply(list[Math.floor(Math.random() * (list.length))]);
};

module.exports.config = {
    name: "8ball",
    description: "Donne une réponse oui/non aléatoirement",
    format: "8ball [votre message fun]",
    canBeUseByBot: false,
    category: "Fun"
};
